### ISSUE TITLE
Game crashes making Golemencer's Bell

### ISSUE THREAD

**Issue by shadowolfyt** [shadowolfyt/AviPack#6]
Game keep crashing when I try to make a golemencer's bell

**Comment by Venomous-Viper1** [comment]
[crash-2017-04-01_16.56.08-client.txt](https://github.com/shadowolfyt/AviPack/files/888104/crash-2017-04-01_16.56.08-client.txt)

**Comment by shadowolfyt** [comment]
Resolved
